name: Saatlik Anket (TR 08:00–22:00, 2 saatte bir)

on:
  schedule:
    # UTC -> TR (UTC+3)
    # 05:05,07:05,09:05,11:05,13:05,15:05,17:05,19:05 UTC
    # 08:05,10:05,12:05,14:05,16:05,18:05,20:05,22:05 TR
    - cron: "5 5,7,9,11,13,15,17,19 * * *"
  workflow_dispatch:

concurrency:
  group: tipquizleri-anket
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check secrets presence
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
        run: |
          for n in X_API_KEY X_API_SECRET X_ACCESS_TOKEN X_ACCESS_SECRET; do
            if [ -z "${!n}" ]; then echo "$n=EMPTY"; else echo "$n=SET"; fi
          done

      - name: Run bot
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          SLOT_TOLERANCE_SEC: "360"   # bot.py için ±6 dk tolerans
        run: |
          [ -f state.json ] || echo '{}' > state.json
          python bot.py
